<?php

function user_form_split_password_user_categories() {
  return array(
    array(
      'name' => 'password',
      'title' => t('change password'),
      'weight' => 1,
    ),
  );
}

function user_form_split_password_form_user_profile_form_alter(&$form, &$form_state) {
  global $user;
  if ($form['#user_category'] != 'password') {
    return;
  }
  $account = $form['#user'];
  $admin = user_access('administer users');
  $pass_reset = isset($_SESSION['pass_reset_' . $account->uid]) && isset($_GET['pass-reset-token']) && ($_GET['pass-reset-token'] == $_SESSION['pass_reset_' . $account->uid]);
  if (empty($pass_reset) && empty($admin)) {
    $form['current_pass_required_values'] = array(
      '#type' => 'value',
      '#value' => array('pass' => t('Password')),
    );
    $form['current_pass'] = array(
      '#type' => 'password',
      '#title' => t('current password'),
    );
    $form['#validate'][] = 'user_validate_current_pass';
  }
  $form['pass'] = array(
    '#type' => 'password_confirm',
  );
}

function user_form_split_password_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_profile_form') {
    if ($form['#user_category'] == 'account') {
      $form['account']['pass']['#access'] = FALSE;
      $form['account']['current_pass_required_values']['#access'] = FALSE;
      $form['account']['current_pass']['#access'] = FALSE;
    }
  }
}

function user_form_split_password_drupal_goto_alter(&$path, $options, $http_response_code) {
  global $user;
  if ($path == 'user/' . $user->uid . '/edit') {
    if (isset($options['query']['pass-reset-token'])) {
      $path = 'user/' . $user->uid . '/edit/password';
    }
  }
}
